=== MrvnAksn/Tux/src/management/dico.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema  version="1.0"
            xmlns:xs="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://univ-grenoble-alpes.fr/dico"
            xmlns="http://univ-grenoble-alpes.fr/dico"
            elementFormDefault="qualified">
    
            <xs:element name="dictionnaire" type="Dico"/>
            <xs:complexType name="Dico">
               <xs:sequence>
                   <xs:element name="word" type="Mot" maxOccurs="unbounded"/>
               </xs:sequence>
            </xs:complexType>
            <xs:complexType name="Mot">
                <xs:simpleContent>
                    <xs:extension base="NosMots">
                        <xs:attribute name="level" type="Niveau" use="required" />
                    </xs:extension>
                </xs:simpleContent>
            </xs:complexType>
            <xs:simpleType name="NosMots">
                <xs:restriction base="xs:string">
                    <xs:pattern value="[a-zA-Zéàèïêëô][a-zA-Zéàèïêëô][a-zA-Zéàèïêëô]([a-zA-Zéàèïêëô])*"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:simpleType name="Niveau">
                <xs:restriction base="xs:int">
                    <xs:pattern value="[1-5]"/>
                </xs:restriction>
            </xs:simpleType>
</xs:schema>

=== MrvnAksn/Tux/src/management/dico.xml
<?xml version="1.0" encoding="UTF-8"?>

<dictionnaire
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://univ-grenoble-alpes.fr/dico'
    xsi:schemaLocation='http://univ-grenoble-alpes.fr/dico file:/home/marvin/Documents/TuxLetterGame/src/management/dico.xsd'>
    
    <word level='2'>bonjour</word>
    <word level='3'>monument</word>
    <word level='1'>nuit</word>
    <word level='4'>physique</word>
    <word level='1'>date</word>
    <word level='1'>mois</word>
    <word level='1'>année</word>
    <word level='4'>araignée</word>
    <word level='5'>sybillin</word>
    <word level='5'>chronophage</word>
    <word level='2'>moteur</word>
    <word level='3'>voiture</word>
    <word level='2'>mot</word>
    <word level='2'>voleur</word>
    <word level='1'>stylo</word>
    <word level='1'>car</word>
    <word level='5'>anticonstitutionnellement</word>
    <word level='5'>anthropologue</word>
    <word level='1'>pot</word>
    <word level='1'>vrai</word>
    <word level='2'>macon</word>
    <word level='2'>colle</word>
    <word level='1'>col</word>
    <word level='3'>beignet</word>
    <word level='2'>crayon</word>
    <word level='3'>trone</word>
    <word level='2'>tige</word>
    <word level='3'>couleur</word>
</dictionnaire>
